name: Build and Publish executable

on:
  - workflow_dispatch
  - push:
      branches:
        - main

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/kbg

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- Build & Push ---
      - name: Build and push kbg
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ github.ref == 'refs/heads/main' && format('{0}:latest', env.IMAGE) || '' }}
